### ISSUE TITLE
개발환경 구축

### ISSUE THREAD

**Issue by Hyeonjun0527** [Apple-Square/moment-frontend#1]
### 🤔 Describe
개발환경을 구축한다.

### ✅ Tasks
- [x] 종속성 라이브러리 추가
- [x] store 생성 (상태 유지)
- [x] index.css 생성 (전체 레이아웃 설정)
- [x] 모든 Route를 관리하는 component 생성
