### ISSUE TITLE
3col 피드 페이지 제작

### ISSUE THREAD

**Issue by rjsdn031** [Apple-Square/moment-frontend#14]
### 📄 Describe
N×3 레이아웃으로  배치되는 피드 리스트 제작

### ✅ Tasks
해야 하는 일에 대한 Tasks를 작성해 주세요.
- [x] 3col 피드 리스트 페이지 제작
- [x] 피드 썸네일 컴포넌트 제작
- [ ] 유저 페이지 연동

### 🙋🏻 More
유저 프로필 제작 전 선행 작업
