### ISSUE TITLE
개별 피드 페이지의 댓글 모달 구현

### ISSUE THREAD

**Issue by rjsdn031** [Apple-Square/moment-frontend#18]
### 📄 Describe
개별 피드 페이지 적용으로 피드의 레이아웃 변경 필요
댓글 슬라이드 모달 적용 필요

### ✅ Tasks
해야 하는 일에 대한 Tasks를 작성해 주세요.
- [x] 댓글 슬라이드 모달 구현
- [ ] 2단 크기 변화 구현(15% %40) 
- [ ] 모달 밖 터치하면 클로징

### 🙋🏻 More
.
