### ISSUE TITLE
백그라운드 적용안되는 오류 해결, 로그인 실패 시 메세지 리팩토링, 로그인 화면 레이아웃 리팩토링

### ISSUE THREAD

**Issue by Hyeonjun0527** [Apple-Square/moment-frontend#34]
### 📄 Describe
백그라운드 적용안되는 오류 해결, 로그인 실패 시 메세지 리팩토링, 로그인 화면 레이아웃 리팩토링

### ✅ Tasks
해야 하는 일에 대한 Tasks를 작성해 주세요.
- [x] 백그라운드 적용안되는 오류
- [x]  로그인 실패 시 메세지 리팩토링
- [x]  로그인 화면 레이아웃 리팩토링

### 🙋🏻 More
더 하고 싶은 말이 있다면 작성해 주세요.
